name: Deploy Templatized Data Environment

on:
  pull_request:
    types: [closed]
    branches:
      - staging
      - main
  push:
    branches:
      - staging
      - main

jobs:
  deploy_data_environment:
    # Only run when PR is merged or on direct push to environment branches
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    env:
      # Read connection secret
      SNOWFLAKE_CONNECTIONS_ADVANCED_DATA_ENGINEERING_SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_CONNECTIONS_ADVANCED_DATA_ENGINEERING_SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_CONNECTIONS_ADVANCED_DATA_ENGINEERING_SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

       # ✅ Compute branch name and deploy environment here (fixes PR merge issue)
+      TARGET_BRANCH: ${{ (github.event_name == 'pull_request' && github.event.pull_request.merged) && github.base_ref || github.ref_name }}
+      DEPLOY_ENV: ${{ (((github.event_name == 'pull_request' && github.event.pull_request.merged) && github.base_ref || github.ref_name) == 'staging') && 'staging' || 'prod' }}


    steps:
      # Checkout step is necessary to access repository files
      - name: Checkout repository
        uses: actions/checkout@v4


       # ✅ Print debug info to verify variable values
+      - name: Print debug context
+        run: |
+          echo "EVENT_NAME=${GITHUB_EVENT_NAME}"
+          echo "REF=${GITHUB_REF}"
+          echo "REF_NAME=${GITHUB_REF_NAME}"
+          echo "BASE_REF=${GITHUB_BASE_REF}"
+          echo "HEAD_REF=${GITHUB_HEAD_REF}"
+          echo "TARGET_BRANCH=${TARGET_BRANCH}"
+          echo "DEPLOY_ENV=${DEPLOY_ENV}"
      
      # Install Snowflake CLI GitHub Action and point to config file
      - name: Install SnowflakeCLI
        uses: snowflakedb/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
          default-config-file-path: "config.toml"

      # Fetch latest changes from the repository to Snowflake
      - name: Fetch latest changes to Snowflake
        run: snow git fetch course_repo.public.advanced_data_engineering_snowflake

      # Deploy templates to the data environment -
      - name: Deploy templates to data environment
        run: |
+          set -euo pipefail
+          echo "Using branch: ${TARGET_BRANCH}"
+          echo "Deploying environment: ${DEPLOY_ENV}"
+
+          snow git execute @advanced_data_engineering_snowflake/branches/${TARGET_BRANCH}/module-1/hamburg_weather/pipeline/data/ \
+            -D "env='${DEPLOY_ENV}'" \
+            --database=COURSE_REPO \
+            --schema=PUBLIC
